# Generated by Django 5.1 on 2024-09-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_info', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='masters_img')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.service')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(to='Web.service'),
        ),
    ]
