# Generated by Django 5.1 on 2024-09-19 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('appointment_date', models.DateTimeField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
